// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: api/example.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AppMessages_Send_FullMethodName = "/api.AppMessages/Send"
)

// AppMessagesClient is the client API for AppMessages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppMessagesClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type appMessagesClient struct {
	cc grpc.ClientConnInterface
}

func NewAppMessagesClient(cc grpc.ClientConnInterface) AppMessagesClient {
	return &appMessagesClient{cc}
}

func (c *appMessagesClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, AppMessages_Send_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMessagesServer is the server API for AppMessages service.
// All implementations must embed UnimplementedAppMessagesServer
// for forward compatibility
type AppMessagesServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedAppMessagesServer()
}

// UnimplementedAppMessagesServer must be embedded to have forward compatible implementations.
type UnimplementedAppMessagesServer struct {
}

func (UnimplementedAppMessagesServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedAppMessagesServer) mustEmbedUnimplementedAppMessagesServer() {}

// UnsafeAppMessagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppMessagesServer will
// result in compilation errors.
type UnsafeAppMessagesServer interface {
	mustEmbedUnimplementedAppMessagesServer()
}

func RegisterAppMessagesServer(s grpc.ServiceRegistrar, srv AppMessagesServer) {
	s.RegisterService(&AppMessages_ServiceDesc, srv)
}

func _AppMessages_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMessagesServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMessages_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMessagesServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppMessages_ServiceDesc is the grpc.ServiceDesc for AppMessages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppMessages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AppMessages",
	HandlerType: (*AppMessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _AppMessages_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/example.proto",
}
