name: Split

on:
  push:
    branches: [ master ]
jobs:
  split:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run
        run: |
          git config pull.rebase true
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-bot"
          bash ./bin/split-linux.sh
